version: "3.9"

services:
  app:
    build: .
    image: indentity:latest
    container_name: indentity-app
    ports:
      - "8080:8080"
    volumes:
      - ./h2-data:/app/data   # mount host folder cho H2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    restart: always
